### ISSUE TITLE
Clarify role and expectations for TAC sponsors of TIs

### ISSUE THREAD

**Issue by marcelamelara** [ossf/tac#263] opened 2024-02-13 22:42 UTC
From a discussion resulting from #262, we identified a couple of points around TAC sponsors for WGs that need clarification in our documentation:

1) TAC sponsors are most helpful in the early stages of a WG
2) We need some rough guidelines/expectations for the role of a TAC sponsor at each stage of a WG.
3) WGs should have a clear way of finding a sponsor (e.g., in the event the initial person leaves/is unable to continue).

Open questions:
What are the expectations for sponsors during the initial stages of a WG, while ensuring TAC members are being stretched too thin?
What is the process for a TAC sponsor to transition to "emeritus" status once the WG has reached a certain maturity level?

**Comment by mlieberman85** [comment] 2024-02-14 17:00
Another open question is what happens if a TAC sponsor becomes out of sync with how the group/project is moving along. I think there should also be a mechanism for TAC sponsor to voice concerns to the rest of the TAC if they feel like a project is off track, if it's moving outside the normal scope of the OpenSSF, is potentially breaking CoC or other rules within OpenSSF, etc.

**Comment by marcelamelara** [comment] 2024-02-14 23:51
It looks like the [TI Gives and Gets](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#sandbox-level-gives--gets) aren't fully aligned with the individual process docs, and may need to be revisited. Should SIGs need a TAC sponsor for the sandbox stage as well? The SIG lifecycle process doc currently only mentions a [governing body](https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md#to-become-sandbox), though the [SIG creation process](https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md#sig-creation-or-change-of-lifecycle-stage) doesn't require TAC approval. Spelling out the role of a TAC sponsor's for a SIG that reports directly to the TAC vs a WG is needed here.

Similarly, what is the scope of the TAC sponsor (and the broader TAC) guidance mentioned in the [Project support](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#project-support-1) section of the Project lifecycle doc?

**Comment by lehors** [comment] 2024-02-20 18:41
SIGs definitely do not need a TAC sponsor. SIGs are (generally) under the governance of their parent WG and the TAC doesn't need to get involved in that at all. This is by design.
I said "generally" because we do allow SIGs to exist under the TAC, in which case the TAC becomes the governing body for the SIG and would obviously been involved. But that's an edge case, not the norm.

**Comment by marcelamelara** [comment] 2024-02-20 19:02
Right, that was my understanding as well. The only place where I think the TAC still have some involvement in the SIG lifecycle, regardless of how it's governed, is through the lifecycle document PR that needs to be submitted to this repo. The doc says "Because no formal approval by the TAC is required the PR can be merged by any TAC or staff member." Might be worth clarifying that that PR doesn't need approval from a majority of the TAC, or something along those lines.

**Comment by SecurityCRob** [comment] 2024-03-19 14:42
I believe this has been accounted for as part of our TI md templates.  Am I correct and we can close this?

**Comment by marcelamelara** [comment] 2024-03-19 18:22
I'm actually not sure we've explicitly answered the questions around expectations and scope past sandbox stage. I don't think we need anything lengthy other than to have a brief comment in the respective lifecycle docs, and possibly make sure that syncs up with the TAC R&Rs.

**Closed** 2024-04-08 13:38 UTC
Labels: documentation, administration, OpsModel
